Ecommerce.Admin/Controllers/CouponController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Domain.Models;
using Ecommerce.Service.Interface;
using EcommerceCommon.Infrastructure.Helper;
using EcommerceCommon.Infrastructure.ViewModel.Admin;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using static EcommerceCommon.Infrastructure.Helper.Helper;
using EcommerceCommon.Infrastructure.Ultil;
using Ecommerce.Service.ViewModels.Admin.ProductAttributeModel;
using Ecommerce.Service.ViewModels.Admin.CouponModel;

namespace Ecommerce.Admin.Controllers
{
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;
        private readonly ICategoryService _categoryService;
        private readonly ICollectionService _collectionService;

        public CouponController(ICouponService couponService, ICategoryService categoryService, ICollectionService collectionService)
        {
            _categoryService = categoryService;

            _couponService = couponService;
            _collectionService = collectionService;

        }
        public async Task<IActionResult> GetCouponList()
        {
            var userId = HttpContext.Session.GetString("userId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var models = await _couponService.GetCouponAdminViewModels();

          
            return View(models);
        }

        // GET: Coupon/Create
        [NoDirectAccess]
        public async Task<IActionResult> Create()
        {
            var userId = HttpContext.Session.GetString("userId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var model = await _couponService.GetAddCouponModel();
            return View(model);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AddCouponViewModel AddCouponViewModel)
        {
            var userId = HttpContext.Session.GetString("userId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            if (ModelState.IsValid)
            {
                if (await _couponService.AddCouponAsync(AddCouponViewModel))
                {
                    return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", await _couponService.GetCouponAdminViewModels()) });

                }
                else
                {
                    return NotFound();
                }
            }
            var model = await _couponService.GetAddCouponViewModels(AddCouponViewModel);
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Create", model) });
        }

        // GET: Category/Edit/5
        public async Task<ActionResult> Edit(Guid id)
        {
            // var coupon = await _couponService.GetByIdAsync(id);
            var userId = HttpContext.Session.GetString("userId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var models = await _couponService.GetEditCouponModel(id);


            if (models == null)
            {
                return NotFound();
            }
            return View(models);
        }

        // POST: Category/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditCouponViewModel editCouponViewModel)
        {
            var userId = HttpContext.Session.GetString("userId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            if (ModelState.IsValid)
            {
                if (await _couponService.EditCouponAsync(editCouponViewModel))
                {
                    return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", await _couponService.GetCouponAdminViewModels())});
                }
                else
                {
                    return NotFound();
                }

            }
            var model = await _couponService.GetEditCouponModel(editCouponViewModel);
            if (model == null)
                return NotFound();
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", model) });
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Guid id)
        {
            var userId = HttpContext.Session.GetString("userId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            if (await _couponService.DeleteCouponAsync(id))
            {
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", await _couponService.GetCouponAdminViewModels()) });
            }
            else
            {
                return NotFound();
            }

        }
    }
}

Ecommerce.Admin/Views/Coupon/Create.cshtml
@model Ecommerce.Service.ViewModels.Admin.CouponModel.AddCouponModel;
@using EcommerceCommon.Infrastructure.Enums

@{
    ViewData["Title"] = "CreateCoupon";
    Layout = null;
}


    <form asp-action="Create" onsubmit="return jQueryAjaxPost(this);" autocomplete="off" enctype="multipart/form-data">
        <div class="form-group text-center">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                            <label class="control-label" asp-for="@Model.AddCouponViewModel.Name"></label>
                        </div>
                        <div class="col-md-8">
                            <input asp-for="@Model.AddCouponViewModel.Name" class="form-control" placeholder="Nhập tên nhà sản xuất">
                            <span asp-validation-for="@Model.AddCouponViewModel.Name" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                            <label class="control-label" asp-for="@Model.AddCouponViewModel.CategoryId"></label>
                        </div>
                        <div class="col-md-8">
                            <select asp-for="@Model.AddCouponViewModel.CategoryId" id="CategoryId">
                                <option value="@null" selected>Không có</option>
                                @foreach (var item in Model.CategoryList)
                                {
                                    <option value="@item.Id">@item.Name</option>
                                }
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group text-center">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                            <label class="control-label" asp-for="@Model.AddCouponViewModel.Amount"></label>
                        </div>
                        <div class="col-md-8">
                            <input type="text" asp-for="@Model.AddCouponViewModel.Amount" class="form-control" placeholder="Nhập số tiền"
                                   oninput='this.value=this.value.replace(/\D/g, "").replace(/\B(?=(\d{3})+(?!\d))/g, ".")'>
                            <span asp-validation-for="@Model.AddCouponViewModel.Amount" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                            <label class="control-label" asp-for="@Model.AddCouponViewModel.NumberApply"></label>
                        </div>
                        <div class="col-md-8">
                            <input type="text" asp-for="@Model.AddCouponViewModel.NumberApply" class="form-control" placeholder="Nhập số lượng"
                                   oninput='this.value=this.value.replace(/\D/g, "")'>
                            <span asp-validation-for="@Model.AddCouponViewModel.NumberApply" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group text-center">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                            <label class="control-label" asp-for="@Model.AddCouponViewModel.StartTime"></label>
                        </div>
                        <div class="col-md-8">
                            <input type="datetime" asp-for="@Model.AddCouponViewModel.StartTime" class="form-control" placeholder="Nhập ngày bắt đầu" data-toggle="datepicker">
                            <span asp-validation-for="@Model.AddCouponViewModel.StartTime" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                            <label class="control-label" asp-for="@Model.AddCouponViewModel.EndTime"></label>
                        </div>
                        <div class="col-md-8">
                            <input type="datetime" asp-for="@Model.AddCouponViewModel.EndTime" class="form-control" placeholder="Nhập ngày kết thúc" data-toggle="datepicker">
                            <span asp-validation-for="@Model.AddCouponViewModel.EndTime" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group text-center">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                            <label class="control-label" asp-for="@Model.AddCouponViewModel.CollectionId"></label>
                        </div>
                        <div class="col-md-4">
                            <select asp-for="@Model.AddCouponViewModel.CollectionId" id="CollectionId">
                                <option value="@null" selected>Không có</option>
                                @foreach (var item in Model.CollectionList)
                                {
                                    <option value="@item.Id">@item.Name</option>
                                }
                            </select>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>

        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Lưu lại</button>
        </div>
    </form>

Ecommerce.Admin/Views/Coupon/Edit.cshtml
@model Ecommerce.Service.ViewModels.Admin.CouponModel.EditCouponModel;
@{
    ViewData["Title"] = "EditCoupon";
    Layout = null;
}


    <form asp-action="Edit" onsubmit="return jQueryAjaxPost(this);" autocomplete="off" enctype="multipart/form-data">
        <input type="hidden" asp-for="@Model.EditCouponViewModel.Id " />


        <div class="form-group">
            <label class="control-label" asp-for="@Model.EditCouponViewModel.Name"></label>
            <div class="input-group">
                <div class="input-group-append">
                    <div class="input-group-text">
                        <i class="fas fa-address-card"></i>
                    </div>
                </div>
                <input asp-for="@Model.EditCouponViewModel.Name" class="form-control" placeholder="Nhập mã giảm giá">
                <span asp-validation-for="@Model.EditCouponViewModel.Name" class="text-danger"></span>
            </div>
            
        </div>
        <div class="form-group">
            <label class="control-label" asp-for="@Model.EditCouponViewModel.Amount"></label>
            <div class="input-group">
                <div class="input-group-append">
                    <div class="input-group-text">
                        <i class="fas fa-pencil-alt"></i>
                    </div>
                </div>
                <input type="text" asp-for="@Model.EditCouponViewModel.Amount" class="form-control" placeholder="Nhập số tiền"
                       oninput='this.value=this.value.replace(/\D/g, "").replace(/\B(?=(\d{3})+(?!\d))/g, ".")'>
                <span asp-validation-for="@Model.EditCouponViewModel.Amount" class="text-danger"></span>
            </div>
            
        </div>
        <div class="form-group">
            <label class="control-label" asp-for="@Model.EditCouponViewModel.NumberApply"></label>
            <div class="input-group">
                <div class="input-group-append">
                    <div class="input-group-text">
                        <i class="fas fa-pencil-alt"></i>
                    </div>
                </div>
                <input type="text" oninput='this.value=this.value.replace(/\D/g, "")' asp-for="@Model.EditCouponViewModel.NumberApply" class="form-control" placeholder="Nhập số lượng">
                <span asp-validation-for="@Model.EditCouponViewModel.NumberApply" class="text-danger"></span>
            </div>
            
        </div>
     

        <div class="form-group text-center">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                            <label class="control-label" asp-for="@Model.EditCouponViewModel.StartTime"></label>
                        </div>
                        <div class="col-md-8">
                            <input type="datetime" asp-for="@Model.EditCouponViewModel.StartTime" class="form-control" placeholder="Nhập ngày bắt đầu" data-toggle="datepicker">
                            <span asp-validation-for="@Model.EditCouponViewModel.StartTime" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                            <label class="control-label" asp-for="@Model.EditCouponViewModel.EndTime"></label>
                        </div>
                        <div class="col-md-8">
                            <input type="datetime" asp-for="@Model.EditCouponViewModel.EndTime" class="form-control" placeholder="Nhập ngày kết thúc" data-toggle="datepicker">
                            <span asp-validation-for="@Model.EditCouponViewModel.EndTime" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="form-group text-center">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                            <label class="control-label" asp-for="@Model.EditCouponViewModel.CollectionId"></label>
                        </div>
                        <div class="col-md-8">
                            <select asp-for="@Model.EditCouponViewModel.CollectionId" id="CollectionId">
                                <option value="@null" selected>Không có</option>
                                @foreach (var item in Model.CollectionList)
                                {
                                    <option value="@item.Id">@item.Name</option>
                                }
                            </select>
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                            <label class="control-label" asp-for="@Model.EditCouponViewModel.CategoryId"></label>
                        </div>
                        <div class="col-md-8">
                            <select asp-for="@Model.EditCouponViewModel.CategoryId" id="CategoryId">
                                <option value="@null" selected>Không có</option>
                                @foreach (var item in Model.CategoryList)
                                {
                                    <option value="@item.Id">@item.Name</option>
                                }
                            </select>
                        </div>
                    </div>
                </div>

            </div>
            </div>

               


                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Lưu lại</button>
                </div>
    </form>

Ecommerce.Admin/Views/Coupon/GetCouponList.cshtml
@model IList<EcommerceCommon.Infrastructure.ViewModel.Admin.CouponAdminViewModel>
@{
    ViewData["Title"] = "GetCategoryList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model)
</div>

Ecommerce.Admin/Views/Coupon/_ViewAll.cshtml
@model IList<EcommerceCommon.Infrastructure.ViewModel.Admin.CouponAdminViewModel>
@{
    var stt = 1;
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mã giảm giá</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Mã giảm giá</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card ">
                        <div class="card-header">
                            <a onclick="showInPopup('@Url.Action("Create","Coupon",null,Context.Request.Scheme)','Tạo mới mã giảm giá')" class="btn btn-success text-white"><i class="fas fa-pencil-alt"></i>Thêm mới</a>
                        </div>

                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="data-table" class="table table-bordered table-striped text-center">
                                <thead>
                                    <tr>
                                        <th style="width:100px !important"> Mã giảm giá </th>
                                        <th style="width:100px !important"> Số tiền giảm </th>
                                        <th style="width:100px !important"> Lượt áp dụng </th>
                                        <th style="width:120px !important"> Danh mục áp dụng</th>
                                        <th style="width:120px !important"> Bộ sưu tập áp dụng</th>
                                        <th style="width:80px !important"> Chức năng </th>
                                    </tr>
                                </thead>

                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td> @item.Name </td>
                                        <td>@item.Amount</td>
                                        <td>@item.NumberApply</td>
                                        <td>@item.CategoryName</td>
                                        <td>@item.CollectionName</td>
                                        <td>
                                            <a onclick="showInPopup('@Url.Action("Edit","Coupon",new { id =item.Id},Context.Request.Scheme)','Sửa Coupon')" class="btn btn-info text-white "><i class="fas fa-random"></i></a>
                                            <form asp-action="Delete" asp-route-id="@item.Id" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
                                                <button type="submit" value="Xóa" class="btn btn-danger">
                                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                    }

                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>