Ecommerce.Web/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Domain.Models;
using Ecommerce.Service.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Ecommerce.Web.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        private readonly ICartDetailService _cartDetailService;
        private readonly IProductAttributeService _productAttributeService;

        public CartController(ICartService cartService,IProductAttributeService productAttributeService, ICartDetailService cartDetailService)
        {
            _cartService = cartService;
            _productAttributeService = productAttributeService;
            _cartDetailService = cartDetailService;
        }
        [HttpGet]
        public async Task<IActionResult> GetCart()
        {
            var userId = HttpContext.Session.GetString("userId");

            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                var model = await _cartService.GetCartViewModelByUserId(new Guid(userId));
                return View(model);
            }
            
        }        
        [HttpPost]
        public async Task<IActionResult> AddCart(Guid ProductId ,Guid? ProductSizeId,Guid? ProductColorId,int quantity)
        {
            var userId = HttpContext.Session.GetString("userId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                if(await _cartService.AddCart(ProductId,ProductSizeId, ProductColorId, quantity, new Guid(userId))){
                    var cartCount = await _cartDetailService.GetCartCount(new Guid(userId));
                    HttpContext.Session.SetString("cartCount", cartCount.ToString());
                    return Json(new { isValid = true,html = cartCount});
                }
                else
                {
                    var product = await _productAttributeService.GetProductAddCartError(ProductId, ProductSizeId, ProductColorId);
                    string msg = "";
                    if (product.CountStock > 0)
                    {
                        msg = "Sản phẩm " + product.ProductName;
                        if(product.Color != null)
                        {
                            msg += " màu " + product.Color;
                        }
                        if(product.Size != null)
                        {
                            msg += " cỡ " + product.Size;
                        }
                        msg +=" chỉ còn " + product.CountStock + " sản phẩm!";
                    }
                    else
                    {
                        msg = "Sản phẩm đã hết hàng !";
                    }
                    return Json(new { isValid = false, html = msg });
                }
            }
        }
        [HttpPut]
        public async Task<IActionResult> UpdateCart(Guid CartDetailId, int Quantity)
        {
            var userId = HttpContext.Session.GetString("userId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                var validate = await _cartService.UpdateCart(CartDetailId, Quantity);
                var cart = await _cartService.GetCartViewModelByUserId(new Guid(userId));
                var cartJson = JsonConvert.SerializeObject(cart);
                var cartCount = await _cartDetailService.GetCartCount(new Guid(userId));
                HttpContext.Session.SetString("cartCount", cartCount.ToString());
                if (validate.IsValid)
                {                    
                    return Json(new {isValid = true, cart = cartJson, cartCount = cartCount });
                }
                else 
                {
                    return Json(new { isValid = false, cart = cartJson, cartCount = cartCount, msg = validate.Message ,quantity = validate.Quantity});
                }
                
            }

        }
        [HttpDelete]
        public async Task<IActionResult> DeleteCart(Guid CartDetailId)
        {
            var userId = HttpContext.Session.GetString("userId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                var validate = await _cartService.DeleteCart(CartDetailId);
                var cart = await _cartService.GetCartViewModelByUserId(new Guid(userId));
                var cartJson = JsonConvert.SerializeObject(cart);
                var cartCount = await _cartDetailService.GetCartCount(new Guid(userId));
                HttpContext.Session.SetString("cartCount", cartCount.ToString());
                
                if (validate.IsValid)
                {
                    return Json(new { isValid = true, cart = cartJson, cartCount = cartCount });
                }
                else
                {
                    return Json(new { isValid = false, cart = cartJson, cartCount = cartCount, msg = validate.Message});
                }
            }
        }
        [HttpPost]
        public async Task<IActionResult> ApplyCoupon(string CodeName)
        {
            var userId = HttpContext.Session.GetString("userId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                var validate = await _cartService.ApplyCoupon(CodeName, new Guid(userId));
                var cart = await _cartService.GetCartViewModelByUserId(new Guid(userId));
                var cartJson = JsonConvert.SerializeObject(cart);
                if (validate.IsValid)
                {
                    return Json(new { isValid = true, cart = cartJson });
                }
                else
                {
                    return Json(new { isValid = false, cart = cartJson, msg = validate.Message});
                }
            }
        }
    }
}

Ecommerce.Web/Controllers/ProductDetailController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Domain.Models;
using Ecommerce.Service.Interface;
using Ecommerce.Service.ViewModels.Web.ProductDetail;
using EcommerceCommon.Infrastructure.Enums;
using EcommerceCommon.Infrastructure.Helper;
using EcommerceCommon.Infrastructure.Ultil;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Ecommerce.Web.Controllers
{
    public class ProductDetailController : Controller
    {
        private readonly IProductService _productService;
        private readonly IProductAttributeService _productAttributeService;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IProductImageService _productImageService;
        private readonly IProductCommentService _productCommentService;
        private readonly IProductCommentReplyService _productCommentReplyService;
        private readonly IProductCommentImageService _productCommentImageService;
        private readonly IProductSizeService _productSizeService;
        private readonly IProductColorService _productColorService;
        public ProductDetailController(IProductService productService, IProductAttributeService productAttributeService,IProductCommentService productCommentService
            , IProductCommentImageService productCommentImageService, IWebHostEnvironment hostEnvironment, IProductImageService productImageService
            , IProductCommentReplyService productCommentReplyService, IProductSizeService productSizeService, IProductColorService productColorService)
        {
            _productService = productService;
            _productAttributeService = productAttributeService;
            this._hostEnvironment = hostEnvironment;
            _productImageService = productImageService;
            _productCommentService = productCommentService;
            _productCommentImageService = productCommentImageService;
            _productCommentReplyService = productCommentReplyService;
            _productSizeService = productSizeService;
            _productColorService = productColorService;
        }
        public async Task<IActionResult> GetProductDetail(Guid ProductAttributeID)
        {
            var products = await _productService.GetProductFirstAttributeByProductAttribute(ProductAttributeID);
            var productImage = await _productImageService.GetProductImageFirstAttribute(ProductAttributeID);
            var productComment = await _productCommentService.GetProductCommentByProductId(products.ProductId);
            var productRating = await _productCommentService.GetProductRatingViewModel(products.ProductId);
            var productColor = await _productColorService.GetProductColorByProductId(products.ProductId);
            var productSize = await _productSizeService.GetProductSizeByProductId(products.ProductId);
            var productSizeFirstAttribute = await _productSizeService.GetListProductSizeByProductColor(products.ProductId,products.ProductColorId);
            var models = new ProductDetailModel()
            {
                ProductFirstAttributeViewModel = products,
                ProductImageFirstAttributeViewModel = productImage,
                ProductComment = new ProductComment(),
                ProductCommentViewModel =productComment,
                ProductRatingViewModel = productRating,
                ProductCommentReply = new ProductCommentReply(),
                ProductSizeViewModel = productSize,
                ProductSizeFirstAttributeViewModel = productSizeFirstAttribute,
                ProductColorViewModel = productColor
            };
            return View(models);
        }
        public async Task<IActionResult> AddProductComment(ProductComment productComment)
        {
            if (productComment.UserId == Guid.Empty)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    // Lưu ảnh vào thư mục wwwroot/image
                    await _productCommentService.AddAsync(productComment);
                    if (productComment.ImageFiles != null)
                    {
                        string wwwRootPath = _hostEnvironment.WebRootPath;
                        foreach (var item in productComment.ImageFiles)
                        {
                            var productCommentImage = new ProductCommentImage();
                            productCommentImage.ImageLink = await Ultil.UploadFileAsync(item, wwwRootPath, "images");
                            productCommentImage.ProductCommentId = productComment.Id;
                            await _productCommentImageService.AddAsync(productCommentImage);
                        }

                    }
                    return Json(new { isValid = true, html = "Nhận xét của bạn đã thành công chờ xét duyệt" });
                }
                return Json(new { isValid = false, html = "Nhận xét thất bại" });
            }
            
        }
        public async Task<IActionResult> AddProductCommentReply(ProductCommentReply productCommentReply)
        {
            if (productCommentReply.UserId == Guid.Empty)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    await _productCommentReplyService.AddAsync(productCommentReply);
                    
                    return Json(new { isValid = true, html = "Nhận xét của bạn đã thành công chờ xét duyệt" });
                }
                return Json(new { isValid = false, html = "Nhận xét thất bại" });
            }
        }
        [HttpPost]
        public async Task<IActionResult> ViewMore(int SkipNum,Guid productCommentId)
        {
            var listReplyComment = await _productCommentReplyService.GetMoreReplyComment(SkipNum, productCommentId);
            string listReplyJson = JsonConvert.SerializeObject(listReplyComment, new IsoDateTimeConverter() { DateTimeFormat = "M/d/yyyy h:mm:ss tt" });
            return Json(new { isValid = true, html = listReplyJson });
        }
        [HttpGet]
        public async Task<IActionResult> GetProductCommentPagination(Guid productId,int skip,int take)
        {
            var listProductComment = await _productCommentService.GetProductCommentPagination(productId, skip, take);
            string listProductCommentJson = JsonConvert.SerializeObject(listProductComment, new IsoDateTimeConverter() { DateTimeFormat = "M/d/yyyy h:mm:ss tt" });
            return Json(new { isValid = true, html = listProductCommentJson });
        }
        [HttpGet]
        public async Task<IActionResult> GetProductDetailByProductColor(Guid productId, Guid productColorId)
        {
            var listImage = await _productImageService.GetProductImageByProductColor(productId, productColorId);
            var productDetail = await _productAttributeService.GetProductAttributeByProductColor(productId, productColorId);
            var listSize = await _productSizeService.GetListProductSizeByProductColor(productId, productColorId);
            var listAllSize = await _productSizeService.GetProductSizeByProductId(productId);
            string listImageJson = JsonConvert.SerializeObject(listImage);
            string productDetailJson = JsonConvert.SerializeObject(productDetail);
            string listSizeJson = JsonConvert.SerializeObject(listSize);
            string listAllSizeJson = JsonConvert.SerializeObject(listAllSize);
            return Json(new { listImage = listImageJson ,productDetail= productDetailJson,listSize=listSizeJson, listAllSize = listAllSizeJson });
        }
        [HttpGet]
        public async Task<IActionResult> GetProductDetailByProductSize(Guid productId, Guid? productColorId,Guid productSizeId)
        {
            var productDetail = await _productAttributeService.GetProductAttributeByProductSize(productId, productColorId,productSizeId);
            string productDetailJson = JsonConvert.SerializeObject(productDetail);
            return Json(new { productDetail = productDetailJson });
        }
    }
}

Ecommerce.Web/Views/Cart/GetCart.cshtml
@model EcommerceCommon.Infrastructure.ViewModel.Web.CartViewModel
@using Microsoft.AspNetCore.Http;
<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col">
                <p class="bread"><span><a href="index.html">Trang chủ</a></span> /<span> Giỏ hàng</span></p>
            </div>
        </div>
    </div>
</div>

@if (Model != null)
{
    @if (Model.CartDetailViewModels.Count != 0)
    {
        <div class="colorlib-product">
            <div class="container">
                <div class="row row-pb-lg order-progress">
                    <div class="col-md-10 offset-md-1">
                        <div class="process-wrap">
                            <div class="process text-center active">
                                <p><span>01</span></p>
                                <h3>Giỏ hàng</h3>
                            </div>
                            <div class="process text-center">
                                <p><span>02</span></p>
                                <h3>Thủ tục thanh toán</h3>
                            </div>
                            <div class="process text-center">
                                <p><span>03</span></p>
                                <h3>Hoàn thành đơn hàng</h3>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-pb-lg">
                    <div class="col-md-12">
                        <div class="product-name d-flex">
                            <div class="one-forth text-left px-4">
                                <span>Thông tin chi tiết sản phẩm</span>
                            </div>
                            <div class="one-eight text-center">
                                <span>Giá bán</span>
                            </div>
                            <div class="one-eight text-center">
                                <span>Số lượng</span>
                            </div>
                            <div class="one-eight text-center px-4">
                                <span>Xóa</span>
                            </div>
                        </div>
                        @foreach (var item in Model.CartDetailViewModels)
                        {
                            <div class="product-cart d-flex">
                                <div class="one-forth">

                                    <div class="display-tc" style="width:100px">
                                        <div class="img-cart">
                                            <img src="~/images/@item.ProductImage" alt="@item.ProductName" />
                                        </div>
                                    </div>
                                    <div class="display-tc">
                                        <h3>
                                            <a href="@Url.Action("GetProductDetail","ProductDetail",new { ProductAttributeId = item.ProductAttributeId})">
                                                @(item.ProductName)
                                                @if (item.ProductColor != null)
                                                {
                                                    <span>,Màu @item.ProductColor</span>
                                                }
                                                @if (item.ProductSize != null)
                                                {
                                                    <span>,Kích cỡ @item.ProductSize</span>
                                                }
                                            </a>
                                            
                                        </h3>
                                    </div>
                                </div>
                                <div class="one-eight text-center">
                                    <div class="display-tc">
                                        <span class="discount-price">@(item.DiscountPrice)₫</span>
                                        <del class="price">@(item.Price)₫ </del>

                                    </div>
                                </div>
                                <div class="one-eight text-center">
                                    <div class="display-tc">
                                        <input type="text" id="quantity" name="quantity" class="form-control input-number text-center"
                                               oninput='this.value=this.value.replace(/\D/g, "")' onchange='updateCart("@item.Id", this.value,this)' value="@item.Quantity">
                                    </div>
                                </div>
                                <div class="one-eight text-center">
                                    <div class="display-tc">
                                        <a onclick='deleteCart("@item.Id", this)' class="closed"></a>
                                    </div>
                                </div>
                            </div>
                        }



                    </div>
                </div>
                <div class="row row-pb-lg">
                    <div class="col-md-12">
                        <div class="total-wrap">
                            <div class="row">
                                <div class="col-md-8">
                                    <form asp-action="ApplyCoupon" asp-controller="Cart" onsubmit="return applyCoupon(this);" autocomplete="off">
                                        <div class="row form-group">
                                            <div class="col-md-9">
                                                <input type="text" name="CodeName" class="form-control input-number" placeholder="Số phiếu giảm giá của bạn ...">
                                            </div>
                                            <div class="col-md-3" style="float:none">
                                                <input type="submit" value="Áp dụng phiếu giảm giá" class="btn btn-primary">
                                            </div>

                                        </div>
                                    </form>
                                </div>
                                <div class="col-md-4 text-center">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="total">
                                                <div class="sub">
                                                    <p><span>Tổng phụ:</span> <span id="NotionalPrice">@(Model.NotionalPrice)₫</span></p>
                                                    @if (Model.DiscountPrice != "0")
                                                    {
                                                        <p id="discount-price">
                                                            <span>Giảm giá:</span>
                                                            <span>
                                                                @(Model.DiscountPrice)₫
                                                            </span>
                                                        </p>
                                                    }

                                                </div>
                                                <div class="grand-total">
                                                    <p><span><strong>Toàn bộ:</strong></span> <span id="TotalPrice">@(Model.TotalPrice)₫</span></p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-12 checkout-btn">
                                            <a asp-controller="CheckOut" asp-action="CheckOut"  class="btn btn-primary">Thanh toán</a>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div id="bar-error">
        </div>
    }
    else
    {
        <div class="empty">
            <p class="empty-note">Không có sản phẩm nào trong giỏ hàng của bạn.</p>
            <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Tiếp tục mua sắm</a>
        </div>
    }

}
else
{
    <div class="empty">
        <p class="empty-note">Không có sản phẩm nào trong giỏ hàng của bạn.</p>
        <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Tiếp tục mua sắm</a>
    </div>
}