Ecommerce.Admin/Controllers/ProductImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Service.Interface;
using Ecommerce.Service.ViewModels.Admin.ProductImageModel;
using EcommerceCommon.Infrastructure.Helper;
using EcommerceCommon.Infrastructure.Ultil;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using static EcommerceCommon.Infrastructure.Helper.Helper;

namespace Ecommerce.Admin.Controllers
{
    public class ProductImageController : Controller
    {
        private readonly IProductImageService _productImageService;
        private readonly IProductColorService _productColorService;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProductImageController(IProductImageService productImageService, IProductColorService productColorService, IWebHostEnvironment hostEnvironment)
        {
            _productImageService = productImageService;
            _productColorService = productColorService;
            _hostEnvironment = hostEnvironment;
        }

        public async Task<IActionResult> GetProductImageList(Guid Id)
        {
            var userId = HttpContext.Session.GetString("userId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var model = await _productImageService.GetProductImageAdminViewModels(Id);
            ViewBag.ProductId = Id;
            return View(model);
        }
        [NoDirectAccess]
        public async Task<IActionResult> Create()
        {
            var userId = HttpContext.Session.GetString("userId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var model = await _productImageService.GetAddProductImageModel();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AddProductImageViewModel AddProductImageViewModel)
        {
            var userId = HttpContext.Session.GetString("userId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            if (ModelState.IsValid)
            {
                if (await _productImageService.AddProductImageAsync(AddProductImageViewModel, _hostEnvironment.WebRootPath))
                {
                    return Json(new { isValid = true, html = Helper.RenderRazorViewAndViewBagToString(this, "_ViewAll", await _productImageService.GetProductImageAdminViewModels(AddProductImageViewModel.ProductId), AddProductImageViewModel.ProductId) });
                }
            }
            var model = await _productImageService.GetAddProductImageModel(AddProductImageViewModel);
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Create", model) });
        }

        // GET: ProductImage/Edit/5
        public async Task<ActionResult> Edit(Guid id)
        {
            var userId = HttpContext.Session.GetString("userId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var model = await _productImageService.GetEditProductImageModel(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // POST: ProductImage/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditProductImageViewModel EditProductImageViewModel)
        {
            var userId = HttpContext.Session.GetString("userId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            if (ModelState.IsValid)
            {
                if (await _productImageService.EditProductImageAsync(EditProductImageViewModel))
                {
                    return Json(new { isValid = true, html = Helper.RenderRazorViewAndViewBagToString(this, "_ViewAll", await _productImageService.GetProductImageAdminViewModels(EditProductImageViewModel.ProductId), EditProductImageViewModel.ProductId) });
                }
                else
                {
                    return NotFound();
                }

            }
            var model = await _productImageService.GetEditProductImageModel(EditProductImageViewModel);
            if (model == null)
                return NotFound();
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", model) });
        }


        // POST: ProductImage/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Guid id, Guid ProductId)
        {
            var userId = HttpContext.Session.GetString("userId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            if (await _productImageService.DeleteProductImageAsync(id, _hostEnvironment.WebRootPath))
            {
                return Json(new { isValid = true, html = Helper.RenderRazorViewAndViewBagToString(this, "_ViewAll", await _productImageService.GetProductImageAdminViewModels(ProductId),ProductId) });
            }
            else
            {
                return NotFound();
            }

        }
    }
}

Ecommerce.Admin/Views/ProductImage/Create.cshtml
@model Ecommerce.Service.ViewModels.Admin.ProductImageModel.AddProductImageModel
@{
    ViewData["Title"] = "CreateProductImage";
    Layout = null;
}


<form asp-action="Create" onsubmit="return jQueryAjaxPost(this);" autocomplete="off" spellcheck="false" enctype="multipart/form-data">
    <input type="hidden" asp-for="@Model.AddProductImageViewModel.ProductId" value="@ViewBag.ProductId" />
    <div class="form-group text-center">
        <div class="row">
            <div class="col-md-6 mr-auto">
                <div class="row">
                    <div class="col-md-4">
                        <label asp-for="@Model.AddProductImageViewModel.ProductColorId" class="control-label"></label>
                    </div>
                    <div class="col-md-6 mr-auto">
                        <select asp-for="@Model.AddProductImageViewModel.ProductColorId">
                            <option value="@null" selected>Không có</option>
                            @foreach (var item in Model.ProductColors)
                            {
                                <option value="@item.Id">@item.Name</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group text-center">
        <div class="row">
            <div class="col-md-12 ">
                <div class="row">
                    <div class="col-md-2 ">
                        <div class="button-container">
                            <a class="button">Chọn ảnh</a>
                            <input type="file" accept="image/" id="ImageFiles" asp-for="@Model.AddProductImageViewModel.ImageFiles" multiple>
                        </div>
                    </div>
                    <div class="col-md-8 mr-auto">

                    </div>
                </div>
                <div class="picture-input">

                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Lưu lại</button>
    </div>
</form>

Ecommerce.Admin/Views/ProductImage/Edit.cshtml
@model Ecommerce.Service.ViewModels.Admin.ProductImageModel.EditProductImageModel
@{
    ViewData["Title"] = "EditProductImage";
    Layout = null;
}


<form asp-action="Edit" onsubmit="return jQueryAjaxPost(this);" autocomplete="off" spellcheck="false" enctype="multipart/form-data">
    <input type="hidden" asp-for="@Model.EditProductImageViewModel.ProductId"/>
    <input type="hidden" asp-for="@Model.EditProductImageViewModel.Id"/>
    <input type="hidden" asp-for="@Model.EditProductImageViewModel.ImageLink"/>
    <div class="form-group text-center">
        <div class="row">
            <div class="col-md-4">
                <div class="row">
                    <div class="col-md-4">
                        <label asp-for="@Model.EditProductImageViewModel.ImageLink" class="control-label"></label>
                    </div>
                    <div class="col-md-6 mr-auto">
                        <img src="~/images/@Model.EditProductImageViewModel.ImageLink" style="height:100px;object-fit:contain;width:100%;" />
                    </div>
                </div>
                
            </div>
            <div class="col-md-4 mr-auto">
                <div class="row">
                    <div class="col-md-4">
                        <label asp-for="@Model.EditProductImageViewModel.ProductColorId" class="control-label"></label>
                    </div>
                    <div class="col-md-6 mr-auto">
                        <select asp-for="@Model.EditProductImageViewModel.ProductColorId">
                            <option value="@null" selected>Không có</option>
                            @foreach (var item in Model.ProductColors)
                            {
                                <option value="@item.Id">@item.Name</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="row">
                    <div class="col-md-4">
                        <label asp-for="@Model.EditProductImageViewModel.IsMainImage" class="control-label"></label>
                    </div>
                    <div class="col-md-2 mr-auto">
                        <input type="checkbox" asp-for="@Model.EditProductImageViewModel.IsMainImage" style="height:24px; width:100%"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Lưu lại</button>
    </div>
</form>

Ecommerce.Admin/Views/ProductImage/GetProductImageList.cshtml
@model IList<EcommerceCommon.Infrastructure.ViewModel.Admin.ProductImageAdminViewModel>
@{
    ViewData["Title"] = "GetProductImageList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model)
</div>

Ecommerce.Admin/Views/ProductImage/_ViewAll.cshtml
@model List<EcommerceCommon.Infrastructure.ViewModel.Admin.ProductImageAdminViewModel>
@{
    var stt = 1;
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Ảnh sản phẩm</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                        <li class="breadcrumb-item"><a href="#">Sản phẩm</a></li>
                        <li class="breadcrumb-item active">Ảnh sản phẩm</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card ">
                        <div class="card-header">
                            <a onclick="showInPopup('@Url.Action("Create","ProductImage",new { ProductId = ViewBag.ProductId},Context.Request.Scheme)','Thêm ảnh')" class="btn btn-success text-white"><i class="fas fa-pencil-alt"></i>Thêm mới</a>
                        </div>

                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="data-table" class="table table-bordered table-striped text-center">
                                <thead>
                                    <tr>
                                        <th style="width:30px !important">STT</th>
                                        <th style="width:200px !important">Tên sản phẩm</th>
                                        <th style="width:100px !important">Màu sắc</th>
                                        <th style="width:100px !important">Ảnh</th>
                                        <th style="width:100px !important">Ảnh chính</th>
                                        <th style="width:100px !important">Chức năng</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td>@stt</td>
                                        <td>@item.ProductName</td>
                                        <td> @item.ColorName</td>
                                        <td><img src="~/images/@item.ImageLink" class="small-img" /></td>
                                        @if (item.IsMainImage)
                                        {
                                            <td>Có</td>
                                        }
                                        else
                                        {
                                            <td>Không</td>
                                        }
                                        <td>
                                            <a onclick="showInPopup('@Url.Action("Edit","ProductImage",new { id =item.Id},Context.Request.Scheme)','Cập nhật ảnh')" title="Cập nhật ảnh" class="btn btn-primary text-white "><i class="fas fa-random"></i></a>
                                            <form asp-action="Delete" asp-route-id="@item.Id" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
                                                <button type="submit" title="Xóa ảnh" class="btn btn-danger">
                                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                        stt++;
                                    }
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>