Ecommerce.Web/Controllers/ProductDetailController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Domain.Models;
using Ecommerce.Service.Interface;
using Ecommerce.Service.ViewModels.Web.ProductDetail;
using EcommerceCommon.Infrastructure.Enums;
using EcommerceCommon.Infrastructure.Helper;
using EcommerceCommon.Infrastructure.Ultil;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Ecommerce.Web.Controllers
{
    public class ProductDetailController : Controller
    {
        private readonly IProductService _productService;
        private readonly IProductAttributeService _productAttributeService;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IProductImageService _productImageService;
        private readonly IProductCommentService _productCommentService;
        private readonly IProductCommentReplyService _productCommentReplyService;
        private readonly IProductCommentImageService _productCommentImageService;
        private readonly IProductSizeService _productSizeService;
        private readonly IProductColorService _productColorService;
        public ProductDetailController(IProductService productService, IProductAttributeService productAttributeService,IProductCommentService productCommentService
            , IProductCommentImageService productCommentImageService, IWebHostEnvironment hostEnvironment, IProductImageService productImageService
            , IProductCommentReplyService productCommentReplyService, IProductSizeService productSizeService, IProductColorService productColorService)
        {
            _productService = productService;
            _productAttributeService = productAttributeService;
            this._hostEnvironment = hostEnvironment;
            _productImageService = productImageService;
            _productCommentService = productCommentService;
            _productCommentImageService = productCommentImageService;
            _productCommentReplyService = productCommentReplyService;
            _productSizeService = productSizeService;
            _productColorService = productColorService;
        }
        public async Task<IActionResult> GetProductDetail(Guid ProductAttributeID)
        {
            var products = await _productService.GetProductFirstAttributeByProductAttribute(ProductAttributeID);
            var productImage = await _productImageService.GetProductImageFirstAttribute(ProductAttributeID);
            var productComment = await _productCommentService.GetProductCommentByProductId(products.ProductId);
            var productRating = await _productCommentService.GetProductRatingViewModel(products.ProductId);
            var productColor = await _productColorService.GetProductColorByProductId(products.ProductId);
            var productSize = await _productSizeService.GetProductSizeByProductId(products.ProductId);
            var productSizeFirstAttribute = await _productSizeService.GetListProductSizeByProductColor(products.ProductId,products.ProductColorId);
            var models = new ProductDetailModel()
            {
                ProductFirstAttributeViewModel = products,
                ProductImageFirstAttributeViewModel = productImage,
                ProductComment = new ProductComment(),
                ProductCommentViewModel =productComment,
                ProductRatingViewModel = productRating,
                ProductCommentReply = new ProductCommentReply(),
                ProductSizeViewModel = productSize,
                ProductSizeFirstAttributeViewModel = productSizeFirstAttribute,
                ProductColorViewModel = productColor
            };
            return View(models);
        }
        public async Task<IActionResult> AddProductComment(ProductComment productComment)
        {
            if (productComment.UserId == Guid.Empty)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    // Lưu ảnh vào thư mục wwwroot/image
                    await _productCommentService.AddAsync(productComment);
                    if (productComment.ImageFiles != null)
                    {
                        string wwwRootPath = _hostEnvironment.WebRootPath;
                        foreach (var item in productComment.ImageFiles)
                        {
                            var productCommentImage = new ProductCommentImage();
                            productCommentImage.ImageLink = await Ultil.UploadFileAsync(item, wwwRootPath, "images");
                            productCommentImage.ProductCommentId = productComment.Id;
                            await _productCommentImageService.AddAsync(productCommentImage);
                        }

                    }
                    return Json(new { isValid = true, html = "Nhận xét của bạn đã thành công chờ xét duyệt" });
                }
                return Json(new { isValid = false, html = "Nhận xét thất bại" });
            }
            
        }
        public async Task<IActionResult> AddProductCommentReply(ProductCommentReply productCommentReply)
        {
            if (productCommentReply.UserId == Guid.Empty)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    await _productCommentReplyService.AddAsync(productCommentReply);
                    
                    return Json(new { isValid = true, html = "Nhận xét của bạn đã thành công chờ xét duyệt" });
                }
                return Json(new { isValid = false, html = "Nhận xét thất bại" });
            }
        }
        [HttpPost]
        public async Task<IActionResult> ViewMore(int SkipNum,Guid productCommentId)
        {
            var listReplyComment = await _productCommentReplyService.GetMoreReplyComment(SkipNum, productCommentId);
            string listReplyJson = JsonConvert.SerializeObject(listReplyComment, new IsoDateTimeConverter() { DateTimeFormat = "M/d/yyyy h:mm:ss tt" });
            return Json(new { isValid = true, html = listReplyJson });
        }
        [HttpGet]
        public async Task<IActionResult> GetProductCommentPagination(Guid productId,int skip,int take)
        {
            var listProductComment = await _productCommentService.GetProductCommentPagination(productId, skip, take);
            string listProductCommentJson = JsonConvert.SerializeObject(listProductComment, new IsoDateTimeConverter() { DateTimeFormat = "M/d/yyyy h:mm:ss tt" });
            return Json(new { isValid = true, html = listProductCommentJson });
        }
        [HttpGet]
        public async Task<IActionResult> GetProductDetailByProductColor(Guid productId, Guid productColorId)
        {
            var listImage = await _productImageService.GetProductImageByProductColor(productId, productColorId);
            var productDetail = await _productAttributeService.GetProductAttributeByProductColor(productId, productColorId);
            var listSize = await _productSizeService.GetListProductSizeByProductColor(productId, productColorId);
            var listAllSize = await _productSizeService.GetProductSizeByProductId(productId);
            string listImageJson = JsonConvert.SerializeObject(listImage);
            string productDetailJson = JsonConvert.SerializeObject(productDetail);
            string listSizeJson = JsonConvert.SerializeObject(listSize);
            string listAllSizeJson = JsonConvert.SerializeObject(listAllSize);
            return Json(new { listImage = listImageJson ,productDetail= productDetailJson,listSize=listSizeJson, listAllSize = listAllSizeJson });
        }
        [HttpGet]
        public async Task<IActionResult> GetProductDetailByProductSize(Guid productId, Guid? productColorId,Guid productSizeId)
        {
            var productDetail = await _productAttributeService.GetProductAttributeByProductSize(productId, productColorId,productSizeId);
            string productDetailJson = JsonConvert.SerializeObject(productDetail);
            return Json(new { productDetail = productDetailJson });
        }
    }
}

Ecommerce.Web/Controllers/ProductListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Service.Interface;
using Ecommerce.Service.ViewModels.Web.ProductList;
using EcommerceCommon.Infrastructure.ViewModel.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Ecommerce.Web.Controllers
{
    public class ProductListController : Controller
    {
        // GET: ProductListController
        private readonly ICategoryService _categoryService;
        private readonly IProductService _productService;
        private readonly IProductColorService _productColorService;
        private readonly IProductSizeService _productSizeService;
        public ProductListController(ICategoryService categoryService, IProductService productService, IProductColorService productColorService, IProductSizeService productSizeService)
        {
            _categoryService = categoryService;
            _productService = productService;
            _productColorService = productColorService;
            _productSizeService = productSizeService;
        }
        public async Task<IActionResult> GetProductByCategory(Guid ID)
        {
            var products = await _productService.GetProductByCategory(ID);
            var categoryProductList = await _categoryService.GetCategoryProductList(ID);
            var listCategoryProductList = await _categoryService.GetListCategoryProductList(categoryProductList.ParentId);
            var listColor = await _productColorService.GetListProductColorViewModel();
            var listSize = await _productSizeService.GetListProductSizeViewModel();
            foreach(var item in listCategoryProductList)
            {
                 item.ProductCount = _productService.GetProductByCategory(item.Id).Result.Count;
                foreach(var item1 in item.CategoryChildren)
                {
                    item1.ProductCount = _productService.GetProductByCategory(item1.Id).Result.Count;
                }
            }
            var models = new ProductListModel()
            {
                ProductHomepage = products,
                CategoryProductListViewModel = categoryProductList,
                ListCategoryProductListViewModel = listCategoryProductList,
                ListProductColorViewModel = listColor,
                ListProductSizeViewModel = listSize
            };
            return View(models);
        }
        [HttpGet]
        public async Task<IActionResult> GetProductPagination(Guid CategoryId, int skip, int take)
        {
            var listProduct = await _productService.GetProductByCategoryPagination(CategoryId,skip,take);
            string listProductJson = JsonConvert.SerializeObject(listProduct);
            return Json(new { listProduct = listProductJson });
        }

        public async Task<IActionResult> SearchProduct(string keyword)
        {
            var product = await _productService.SearchProduct(keyword);
            ViewBag.ListColor = await _productColorService.GetListProductColorViewModel();
            ViewBag.ListSize = await _productSizeService.GetListProductSizeViewModel();
            return View(product);
        }


    }
}

Ecommerce.Web/ViewComponents/BrandViewComponent.cs
using Ecommerce.Service.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ecommerce.Web.ViewComponents
{
    public class BrandViewComponent : ViewComponent
    {

        private readonly IManufacturerService _manufacturerService;
        //private readonly IHttpContextAccessor _httpContextAccessor;

        public BrandViewComponent(IManufacturerService manufacturerService)
        {
            _manufacturerService = manufacturerService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {

            var models = await _manufacturerService.GetManufacturerHomepage();
            return View(models);
        }
    }
}

Ecommerce.Web/Views/ProductList/GetProductByCategory.cshtml
@model Ecommerce.Service.ViewModels.Web.ProductList.ProductListModel
@{
    ViewData["Title"] = "GetProductByCategoryLevel1";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var productPerPage = 4;
    var productNumber = Model.ProductHomepage.Count();
    var PageNumber = Math.Ceiling((double)(productNumber) / (double)(productPerPage));
}

<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col">
                <p class="bread">
                    <span>
                        <a asp-controller="Home" asp-action="Index">
                            Trang chủ
                        </a>
                    </span>
                    /
                    <span>
                        @Model.CategoryProductListViewModel.Name
                    </span>
                </p>
            </div>
        </div>
    </div>
</div>

<div class="breadcrumbs-two">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="breadcrumbs-category">
                    <img src="~/images/@Model.CategoryProductListViewModel.URLImage" />
                </div>
                <div class="menu text-center">
                    <p>
                        <a href="#">
                            Hàng Mới
                        </a>
                        <a href="#">
                            Bán Chạy
                        </a>
                        <a href="#">
                            Giảm Giá Nhiều
                        </a>
                        <a href="#">
                            Giá Thấp
                        </a>
                        <a href="#">
                            Giá Cao
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="product-list">
    <div class="container">
        <div class="row">
            <div class="product-list-left">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="side border mb-1">
                            <h3>
                                Danh Mục Sản Phẩm
                            </h3>
                            <ul>
                                @if (Model.ListCategoryProductListViewModel.Count != 0)
                                {
                                    @foreach (var item in Model.ListCategoryProductListViewModel)
                                    {
                                        if (item.Id == Model.CategoryProductListViewModel.Id)
                                        {
                                            <li class="is-category">
                                                <a asp-controller="ProductList" asp-action="GetProductByCategory" asp-route-id="@item.Id">
                                                    @item.Name
                                                    <span class="product-count">(@item.ProductCount)</span>
                                                </a>
                                            </li>
                                            @if (item.CategoryChildren.Count != 0)
                                            {
                                                @foreach (var item1 in item.CategoryChildren)
                                                {
                                                    <li class="is-child">
                                                        <a asp-controller="ProductList" asp-action="GetProductByCategory" asp-route-id="@item1.Id">
                                                            @item1.Name
                                                            <span class="product-count">(@item1.ProductCount)</span>
                                                        </a>
                                                    </li>
                                                }
                                            }
                                        }
                                        else
                                        {
                                            <li>
                                                <a asp-controller="ProductList" asp-action="GetProductByCategory" asp-route-id="@item.Id">
                                                    @item.Name
                                                    <span class="product-count">(@item.ProductCount)</span>
                                                </a>
                                            </li>
                                            @if (item.CategoryChildren.Count != 0)
                                            {
                                                @foreach (var item1 in item.CategoryChildren)
                                                {
                                                    <li class="is-child">
                                                        <a asp-controller="ProductList" asp-action="GetProductByCategory" asp-route-id="@item1.Id">
                                                            @item1.Name
                                                            <span class="product-count">(@item1.ProductCount)</span>
                                                        </a>
                                                    </li>
                                                }
                                            }
                                        }
                                    }
                                }

                            </ul>
                        </div>
                    </div>
                    @if (Model.ListProductSizeViewModel.Count != 0)
                    {
                        <div class="col-sm-12">
                            <div class="side border mb-1">
                                <h3>
                                    Kích thước
                                </h3>
                                <div class="block-26 mb-2">
                                    <ul>
                                        @foreach (var item in Model.ListProductSizeViewModel)
                                        {
                                            <li><a href="#">@item.Name</a></li>
                                        }
                                    </ul>
                                </div>
                            </div>
                        </div>
                    }
                    @if (Model.ListProductColorViewModel.Count != 0)
                    {
                        <div class="col-sm-12">
                            <div class="side border mb-1">
                                <h3>
                                    Màu sắc
                                </h3>
                                <ul>
                                    @foreach (var item in Model.ListProductColorViewModel)
                                    {
                                        <li><a href="#">@item.Name</a></li>
                                    }
                                </ul>
                            </div>
                        </div>
                    }



                </div>
            </div>
            <div class="product-list-right">
                <div class="row row-pb-md paginate">
                    @foreach (var item in Model.ProductHomepage)
                    {
                        if (Model.ProductHomepage.IndexOf(item) == productPerPage)
                        {
                            break;
                        }
                        if (item.ProductHomepageAttributeViewModel.Count != 0)
                        {
                            <div class="col-md-3 text-left pb-3 item-paginate">
                                <div class="product-entry border">
                                    <div class="productimg">
                                        <a href="@Url.Action("GetProductDetail","ProductDetail",new { ProductAttributeId = item.ProductHomepageAttributeViewModel[0].Id})" class="prod-img">
                                            <img src="~/images/@item.ProductHomepageAttributeViewModel[0].UrlImage" class="img-fluid" alt="@item.Name">
                                        </a>
                                    </div>
                                    @if (item.ProductHomepageAttributeViewModel.Count > 1)
                                    {
                                        <ul class=" product-image-color">
                                            @foreach (var item1 in item.ProductHomepageAttributeViewModel)
                                            {
                                                <li style="width:34px ; height:32px">
                                                    <a class="prod-img color" href="@Url.Action("GetProductDetail","ProductDetail",new { ProductAttributeId = item1.Id})" id="@item1.Id">
                                                        <img src="~/images/@item1.UrlImage" class="img-fluid" alt="@item.Name" style="width:32px; height:32px;">
                                                    </a>
                                                </li>
                                            }
                                        </ul>
                                    }
                                    <div class="desc">
                                        <h2 class="text-center product-title">
                                            <a href="@Url.Action("GetProductDetail","ProductDetail",new { ProductAttributeId = item.ProductHomepageAttributeViewModel[0].Id})" class="prod-img">
                                                @item.Name
                                            </a>
                                        </h2>
                                        <span class="text-center price">
                                            <del>
                                                <span class="price-amount ">@item.ProductHomepageAttributeViewModel[0].Price₫</span>
                                            </del>
                                            <ins>
                                                <span class="price-amount ">
                                                    @item.ProductHomepageAttributeViewModel[0].PriceSale₫
                                                    @*<span class="sale-tag ">-@Math.Round(((1 - @item.PriceSale / @item.Price) * 100), 0)%</span>*@
                                                </span>
                                                <span class="percent deal">-@item.ProductHomepageAttributeViewModel[0].PercentSale%</span>
                                            </ins>
                                        </span>

                                    </div>
                                </div>
                            </div>
                        }
                    }

                </div>
                <div class="row">
                    <div class="col-md-12">
                        <ul class="Navigation__Wrapper-dgcpmq-0 kiFxlu" style="justify-content: flex-end;">
                            @if (PageNumber > 1)
                            {
                                <li><a class="btnum prev"><svg fill="currentColor" preserveAspectRatio="xMidYMid meet" height="1em" width="1em" viewBox="0 0 40 40" style="vertical-align: middle;"><g><path d="m26.5 12.1q0 0.3-0.2 0.6l-8.8 8.7 8.8 8.8q0.2 0.2 0.2 0.5t-0.2 0.5l-1.1 1.1q-0.3 0.3-0.6 0.3t-0.5-0.3l-10.4-10.4q-0.2-0.2-0.2-0.5t0.2-0.5l10.4-10.4q0.3-0.2 0.5-0.2t0.6 0.2l1.1 1.1q0.2 0.2 0.2 0.5z"></path></g></svg></a></li>
                                for (int i = 1; i <= PageNumber; i++)
                                {
                                    if (i == 1)
                                    {
                                        <li><a class="btnum active" data-attr="@i">@i</a></li>
                                    }
                                    else
                                    {
                                        <li><a class="btnum " data-attr="@i" onclick="paginate(this,@PageNumber,@productPerPage,'@Model.CategoryProductListViewModel.Id')">@i</a></li>
                                    }
                                }
                                <li><a class="btnum next" onclick="paginate(this,@PageNumber,@productPerPage,'@Model.CategoryProductListViewModel.Id')"><svg fill="currentColor" preserveAspectRatio="xMidYMid meet" height="1em" width="1em" viewBox="0 0 40 40" style="vertical-align: middle;"><g><path d="m26.3 21.4q0 0.3-0.2 0.5l-10.4 10.4q-0.3 0.3-0.6 0.3t-0.5-0.3l-1.1-1.1q-0.2-0.2-0.2-0.5t0.2-0.5l8.8-8.8-8.8-8.7q-0.2-0.3-0.2-0.6t0.2-0.5l1.1-1.1q0.3-0.2 0.5-0.2t0.6 0.2l10.4 10.4q0.2 0.2 0.2 0.5z"></path></g></svg></a></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@await Component.InvokeAsync("Brand")